sudo: required

# blocklist
branches:
  except:
    - dev
  only:
    - master

services:
  - docker

before_install:
  - docker build -t paihari/binance-buylow -f Dockerfile .

script:
  - ./mvnw test -B -Dspring.profiles.active=dev

deploy:
  provider: elasticbeanstalk
  region: "$AWS_REGION"
  app: "$AWS_APP"
  env: "$AWS_ENV"
  bucket_name: "$AWS_BUCKET"
  bucket_path: "$AWS_BUCKET_PATH"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"


