sudo: required
services:
  - docker

before_install:
  - docker build -t paihari/binance-buylow -f Dockerfile .

script:
  - docker run -e CI=true paihari/binance-buylow npm run test -- --watchAll=false
