sudo: required
services:
  - docker

before_install:
  - docker build -t paihari/binance-buylow -f Dockerfile .

script:
  - ./mvnw test -B --spring.profiles.active=dev

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "buylow-app"
  env: "BuylowApp-env"
  bucket_name: "elasticbeanstalk-us-east-1-898024814010"
  bucket_path: "buylow-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"


